name: CI

on:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn

      - name: Run CI Tests
        run: yarn test

      - name: Run EsLint
        run: yarn lint:check

      - name: Run Prettier
        run: yarn format:check
